<?xml version="1.0"?>
<robot name="rover" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="body_mass" value="4"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_diameter" value="0.2"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  <xacro:property name="ns" value="rover" />
  <xacro:include filename="$(find rover_description)/urdf/rover.gazebo.xacro" />
  <xacro:property name="mesh_path" value="$(find rover_description)/models" />

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" />
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.2 0.5 0.05"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.2 0.5 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${body_mass}"/>
      <inertia ixx="0.16666700" ixy="0.0" ixz="0.0" iyy="0.16666700" iyz="0.0" izz="0.16666700"/>
    </inertial>
  </link>

  <link name="right_wheel1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
      <geometry>
        <mesh filename="file://${mesh_path}/meshes/14-010-p006.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
    </collision> 
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.0013166667" ixy="0.0" ixz="0.0" iyy="0.0013166667" iyz="0.0" izz="0.0025"/>
    </inertial>   
  </link>

  <joint name="base_to_right1" type="continuous">
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
    <dynamics damping="0.7"/>
    <parent link="base_link"/>
    <child link="right_wheel1"/>
    <axis xyz="1 0 0"/>
    <origin xyz="0.12 0.15 0"/>
  </joint>

   <link name="left_wheel1">
    <visual>
      <geometry>
        <mesh filename="file://${mesh_path}/meshes/14-010-p006.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.0013166667" ixy="0.0" ixz="0.0" iyy="0.0013166667" iyz="0.0" izz="0.0025"/>
    </inertial>    
  </link>

  <joint name="base_to_left1" type="continuous">
    <axis xyz="1 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
    <dynamics damping="0.7"/>
    <parent link="base_link"/>
    <child link="left_wheel1"/>
    <origin xyz="-0.12 0.15 0"/>
  </joint>

  <link name="right_wheel2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
      <geometry>
        <mesh filename="file://${mesh_path}/meshes/14-010-p006.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
    </collision>   
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.0013166667" ixy="0.0" ixz="0.0" iyy="0.0013166667" iyz="0.0" izz="0.0025"/>
    </inertial>     
  </link>

  <joint name="base_to_right2" type="continuous">
    <axis xyz="1 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
    <dynamics damping="0.7"/>
    <parent link="base_link"/>
    <child link="right_wheel2"/>
    <origin xyz="0.12 -0.15 0"/>
  </joint>

  <link name="left_wheel2">
    <visual>
      <geometry>
        <mesh filename="file://${mesh_path}/meshes/14-010-p006.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
    </collision> 
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.0013166667" ixy="0.0" ixz="0.0" iyy="0.0013166667" iyz="0.0" izz="0.0025"/>
    </inertial>       
  </link>

  <joint name="base_to_left2" type="continuous">
    <axis xyz="1 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
    <dynamics damping="0.7"/>
    <parent link="base_link"/>
    <child link="left_wheel2"/>
    <origin xyz="-0.12 -0.15 0"/>
  </joint>

  <transmission name="right_wheel1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_right1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_wheel1_motor">
    </actuator>
  </transmission>
  <transmission name="right_wheel2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_right2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_wheel2_motor">
    </actuator>
  </transmission>
  <transmission name="left_wheel1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_left1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_wheel1_motor">
    </actuator>
  </transmission>
  <transmission name="left_wheel2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_left2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_wheel2_motor">
    </actuator>
  </transmission>

</robot>
